// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: interface.proto
#ifndef GRPC_interface_2eproto__INCLUDED
#define GRPC_interface_2eproto__INCLUDED

#include "interface.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace PoseService {

// Define the gRPC service
class PoseService final {
 public:
  static constexpr char const* service_full_name() {
    return "PoseService.PoseService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // RPC method for sending coordinates and receiving a response
    virtual ::grpc::Status SendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::PoseService::CoordinatesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PoseService::CoordinatesResponse>> AsyncSendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PoseService::CoordinatesResponse>>(AsyncSendCoordinatesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PoseService::CoordinatesResponse>> PrepareAsyncSendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PoseService::CoordinatesResponse>>(PrepareAsyncSendCoordinatesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // RPC method for sending coordinates and receiving a response
      virtual void SendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest* request, ::PoseService::CoordinatesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest* request, ::PoseService::CoordinatesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PoseService::CoordinatesResponse>* AsyncSendCoordinatesRaw(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PoseService::CoordinatesResponse>* PrepareAsyncSendCoordinatesRaw(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::PoseService::CoordinatesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PoseService::CoordinatesResponse>> AsyncSendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PoseService::CoordinatesResponse>>(AsyncSendCoordinatesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PoseService::CoordinatesResponse>> PrepareAsyncSendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PoseService::CoordinatesResponse>>(PrepareAsyncSendCoordinatesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest* request, ::PoseService::CoordinatesResponse* response, std::function<void(::grpc::Status)>) override;
      void SendCoordinates(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest* request, ::PoseService::CoordinatesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::PoseService::CoordinatesResponse>* AsyncSendCoordinatesRaw(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::PoseService::CoordinatesResponse>* PrepareAsyncSendCoordinatesRaw(::grpc::ClientContext* context, const ::PoseService::CoordinatesRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendCoordinates_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // RPC method for sending coordinates and receiving a response
    virtual ::grpc::Status SendCoordinates(::grpc::ServerContext* context, const ::PoseService::CoordinatesRequest* request, ::PoseService::CoordinatesResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendCoordinates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendCoordinates() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendCoordinates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCoordinates(::grpc::ServerContext* /*context*/, const ::PoseService::CoordinatesRequest* /*request*/, ::PoseService::CoordinatesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendCoordinates(::grpc::ServerContext* context, ::PoseService::CoordinatesRequest* request, ::grpc::ServerAsyncResponseWriter< ::PoseService::CoordinatesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendCoordinates<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendCoordinates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendCoordinates() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::PoseService::CoordinatesRequest, ::PoseService::CoordinatesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::PoseService::CoordinatesRequest* request, ::PoseService::CoordinatesResponse* response) { return this->SendCoordinates(context, request, response); }));}
    void SetMessageAllocatorFor_SendCoordinates(
        ::grpc::MessageAllocator< ::PoseService::CoordinatesRequest, ::PoseService::CoordinatesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::PoseService::CoordinatesRequest, ::PoseService::CoordinatesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendCoordinates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCoordinates(::grpc::ServerContext* /*context*/, const ::PoseService::CoordinatesRequest* /*request*/, ::PoseService::CoordinatesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendCoordinates(
      ::grpc::CallbackServerContext* /*context*/, const ::PoseService::CoordinatesRequest* /*request*/, ::PoseService::CoordinatesResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendCoordinates<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendCoordinates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendCoordinates() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendCoordinates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCoordinates(::grpc::ServerContext* /*context*/, const ::PoseService::CoordinatesRequest* /*request*/, ::PoseService::CoordinatesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendCoordinates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendCoordinates() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendCoordinates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCoordinates(::grpc::ServerContext* /*context*/, const ::PoseService::CoordinatesRequest* /*request*/, ::PoseService::CoordinatesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendCoordinates(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendCoordinates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendCoordinates() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendCoordinates(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendCoordinates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCoordinates(::grpc::ServerContext* /*context*/, const ::PoseService::CoordinatesRequest* /*request*/, ::PoseService::CoordinatesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendCoordinates(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendCoordinates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendCoordinates() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::PoseService::CoordinatesRequest, ::PoseService::CoordinatesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::PoseService::CoordinatesRequest, ::PoseService::CoordinatesResponse>* streamer) {
                       return this->StreamedSendCoordinates(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendCoordinates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendCoordinates(::grpc::ServerContext* /*context*/, const ::PoseService::CoordinatesRequest* /*request*/, ::PoseService::CoordinatesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendCoordinates(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::PoseService::CoordinatesRequest,::PoseService::CoordinatesResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendCoordinates<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendCoordinates<Service > StreamedService;
};

}  // namespace PoseService


#endif  // GRPC_interface_2eproto__INCLUDED
