// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interface.proto
// Protobuf C++ Version: 5.28.1

#include "interface.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace PoseService {

inline constexpr CoordinatesResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CoordinatesResponse::CoordinatesResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CoordinatesResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CoordinatesResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CoordinatesResponseDefaultTypeInternal() {}
  union {
    CoordinatesResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CoordinatesResponseDefaultTypeInternal _CoordinatesResponse_default_instance_;

inline constexpr CoordinatesRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : position_x_{0},
        position_y_{0},
        position_z_{0},
        orientation_roll_{0},
        orientation_pitch_{0},
        orientation_yaw_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CoordinatesRequest::CoordinatesRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CoordinatesRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CoordinatesRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CoordinatesRequestDefaultTypeInternal() {}
  union {
    CoordinatesRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CoordinatesRequestDefaultTypeInternal _CoordinatesRequest_default_instance_;
}  // namespace PoseService
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_interface_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_interface_2eproto = nullptr;
const ::uint32_t
    TableStruct_interface_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::PoseService::CoordinatesRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::PoseService::CoordinatesRequest, _impl_.position_x_),
        PROTOBUF_FIELD_OFFSET(::PoseService::CoordinatesRequest, _impl_.position_y_),
        PROTOBUF_FIELD_OFFSET(::PoseService::CoordinatesRequest, _impl_.position_z_),
        PROTOBUF_FIELD_OFFSET(::PoseService::CoordinatesRequest, _impl_.orientation_roll_),
        PROTOBUF_FIELD_OFFSET(::PoseService::CoordinatesRequest, _impl_.orientation_pitch_),
        PROTOBUF_FIELD_OFFSET(::PoseService::CoordinatesRequest, _impl_.orientation_yaw_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::PoseService::CoordinatesResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::PoseService::CoordinatesResponse, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::PoseService::CoordinatesRequest)},
        {14, -1, -1, sizeof(::PoseService::CoordinatesResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::PoseService::_CoordinatesRequest_default_instance_._instance,
    &::PoseService::_CoordinatesResponse_default_instance_._instance,
};
const char descriptor_table_protodef_interface_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017interface.proto\022\013PoseService\"\236\001\n\022Coord"
    "inatesRequest\022\022\n\nposition_x\030\001 \001(\002\022\022\n\npos"
    "ition_y\030\002 \001(\002\022\022\n\nposition_z\030\003 \001(\002\022\030\n\020ori"
    "entation_roll\030\004 \001(\002\022\031\n\021orientation_pitch"
    "\030\005 \001(\002\022\027\n\017orientation_yaw\030\006 \001(\002\"&\n\023Coord"
    "inatesResponse\022\017\n\007message\030\001 \001(\t2c\n\013PoseS"
    "ervice\022T\n\017SendCoordinates\022\037.PoseService."
    "CoordinatesRequest\032 .PoseService.Coordin"
    "atesResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_interface_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_interface_2eproto = {
    false,
    false,
    340,
    descriptor_table_protodef_interface_2eproto,
    "interface.proto",
    &descriptor_table_interface_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_interface_2eproto::offsets,
    file_level_enum_descriptors_interface_2eproto,
    file_level_service_descriptors_interface_2eproto,
};
namespace PoseService {
// ===================================================================

class CoordinatesRequest::_Internal {
 public:
};

CoordinatesRequest::CoordinatesRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PoseService.CoordinatesRequest)
}
CoordinatesRequest::CoordinatesRequest(
    ::google::protobuf::Arena* arena, const CoordinatesRequest& from)
    : CoordinatesRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CoordinatesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CoordinatesRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, position_x_),
           0,
           offsetof(Impl_, orientation_yaw_) -
               offsetof(Impl_, position_x_) +
               sizeof(Impl_::orientation_yaw_));
}
CoordinatesRequest::~CoordinatesRequest() {
  // @@protoc_insertion_point(destructor:PoseService.CoordinatesRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CoordinatesRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    CoordinatesRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_CoordinatesRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &CoordinatesRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<CoordinatesRequest>(),
            ::google::protobuf::Message::GetNewImpl<CoordinatesRequest>(),
            ::google::protobuf::Message::GetClearImpl<CoordinatesRequest>(), &CoordinatesRequest::ByteSizeLong,
                &CoordinatesRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_._cached_size_),
            false,
        },
        &CoordinatesRequest::kDescriptorMethods,
        &descriptor_table_interface_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* CoordinatesRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2> CoordinatesRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PoseService::CoordinatesRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float position_x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.position_x_)}},
    // float position_y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.position_y_)}},
    // float position_z = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.position_z_)}},
    // float orientation_roll = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 63, 0, PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.orientation_roll_)}},
    // float orientation_pitch = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.orientation_pitch_)}},
    // float orientation_yaw = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 63, 0, PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.orientation_yaw_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // float position_x = 1;
    {PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.position_x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float position_y = 2;
    {PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.position_y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float position_z = 3;
    {PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.position_z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float orientation_roll = 4;
    {PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.orientation_roll_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float orientation_pitch = 5;
    {PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.orientation_pitch_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float orientation_yaw = 6;
    {PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.orientation_yaw_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CoordinatesRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:PoseService.CoordinatesRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.position_x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.orientation_yaw_) -
      reinterpret_cast<char*>(&_impl_.position_x_)) + sizeof(_impl_.orientation_yaw_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CoordinatesRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CoordinatesRequest& this_ = static_cast<const CoordinatesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CoordinatesRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CoordinatesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:PoseService.CoordinatesRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float position_x = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_position_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_position_x(), target);
          }

          // float position_y = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_position_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_position_y(), target);
          }

          // float position_z = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_position_z()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_position_z(), target);
          }

          // float orientation_roll = 4;
          if (::absl::bit_cast<::uint32_t>(this_._internal_orientation_roll()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                4, this_._internal_orientation_roll(), target);
          }

          // float orientation_pitch = 5;
          if (::absl::bit_cast<::uint32_t>(this_._internal_orientation_pitch()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                5, this_._internal_orientation_pitch(), target);
          }

          // float orientation_yaw = 6;
          if (::absl::bit_cast<::uint32_t>(this_._internal_orientation_yaw()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                6, this_._internal_orientation_yaw(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:PoseService.CoordinatesRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CoordinatesRequest::ByteSizeLong(const MessageLite& base) {
          const CoordinatesRequest& this_ = static_cast<const CoordinatesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CoordinatesRequest::ByteSizeLong() const {
          const CoordinatesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:PoseService.CoordinatesRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float position_x = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_position_x()) != 0) {
              total_size += 5;
            }
            // float position_y = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_position_y()) != 0) {
              total_size += 5;
            }
            // float position_z = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_position_z()) != 0) {
              total_size += 5;
            }
            // float orientation_roll = 4;
            if (::absl::bit_cast<::uint32_t>(this_._internal_orientation_roll()) != 0) {
              total_size += 5;
            }
            // float orientation_pitch = 5;
            if (::absl::bit_cast<::uint32_t>(this_._internal_orientation_pitch()) != 0) {
              total_size += 5;
            }
            // float orientation_yaw = 6;
            if (::absl::bit_cast<::uint32_t>(this_._internal_orientation_yaw()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CoordinatesRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CoordinatesRequest*>(&to_msg);
  auto& from = static_cast<const CoordinatesRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PoseService.CoordinatesRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_position_x()) != 0) {
    _this->_impl_.position_x_ = from._impl_.position_x_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_position_y()) != 0) {
    _this->_impl_.position_y_ = from._impl_.position_y_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_position_z()) != 0) {
    _this->_impl_.position_z_ = from._impl_.position_z_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_orientation_roll()) != 0) {
    _this->_impl_.orientation_roll_ = from._impl_.orientation_roll_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_orientation_pitch()) != 0) {
    _this->_impl_.orientation_pitch_ = from._impl_.orientation_pitch_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_orientation_yaw()) != 0) {
    _this->_impl_.orientation_yaw_ = from._impl_.orientation_yaw_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CoordinatesRequest::CopyFrom(const CoordinatesRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PoseService.CoordinatesRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CoordinatesRequest::InternalSwap(CoordinatesRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.orientation_yaw_)
      + sizeof(CoordinatesRequest::_impl_.orientation_yaw_)
      - PROTOBUF_FIELD_OFFSET(CoordinatesRequest, _impl_.position_x_)>(
          reinterpret_cast<char*>(&_impl_.position_x_),
          reinterpret_cast<char*>(&other->_impl_.position_x_));
}

::google::protobuf::Metadata CoordinatesRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CoordinatesResponse::_Internal {
 public:
};

CoordinatesResponse::CoordinatesResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PoseService.CoordinatesResponse)
}
inline PROTOBUF_NDEBUG_INLINE CoordinatesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::PoseService::CoordinatesResponse& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

CoordinatesResponse::CoordinatesResponse(
    ::google::protobuf::Arena* arena,
    const CoordinatesResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CoordinatesResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PoseService.CoordinatesResponse)
}
inline PROTOBUF_NDEBUG_INLINE CoordinatesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void CoordinatesResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CoordinatesResponse::~CoordinatesResponse() {
  // @@protoc_insertion_point(destructor:PoseService.CoordinatesResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CoordinatesResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    CoordinatesResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_CoordinatesResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &CoordinatesResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<CoordinatesResponse>(),
            ::google::protobuf::Message::GetNewImpl<CoordinatesResponse>(),
            ::google::protobuf::Message::GetClearImpl<CoordinatesResponse>(), &CoordinatesResponse::ByteSizeLong,
                &CoordinatesResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(CoordinatesResponse, _impl_._cached_size_),
            false,
        },
        &CoordinatesResponse::kDescriptorMethods,
        &descriptor_table_interface_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* CoordinatesResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 47, 2> CoordinatesResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PoseService::CoordinatesResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CoordinatesResponse, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(CoordinatesResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\37\7\0\0\0\0\0\0"
    "PoseService.CoordinatesResponse"
    "message"
  }},
};

PROTOBUF_NOINLINE void CoordinatesResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:PoseService.CoordinatesResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CoordinatesResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CoordinatesResponse& this_ = static_cast<const CoordinatesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CoordinatesResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CoordinatesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:PoseService.CoordinatesResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string message = 1;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PoseService.CoordinatesResponse.message");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:PoseService.CoordinatesResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CoordinatesResponse::ByteSizeLong(const MessageLite& base) {
          const CoordinatesResponse& this_ = static_cast<const CoordinatesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CoordinatesResponse::ByteSizeLong() const {
          const CoordinatesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:PoseService.CoordinatesResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string message = 1;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CoordinatesResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CoordinatesResponse*>(&to_msg);
  auto& from = static_cast<const CoordinatesResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PoseService.CoordinatesResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CoordinatesResponse::CopyFrom(const CoordinatesResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PoseService.CoordinatesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CoordinatesResponse::InternalSwap(CoordinatesResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata CoordinatesResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace PoseService
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_interface_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
